### ISSUE TITLE
Usage with Docker

### ISSUE THREAD

**Issue by agustisanchez** [vishnubob/wait-for-it#57]
In order to use it with Docker and docker-compose,
place it alongside `Dockerfile`, build it into the image with exec permissions and reference it in `docker-compose.yml`.

```
- Dockerfile
- wait-for-it.sh
```

```Dockerfile
#Dockerfile
...
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
...
```

```yaml
#docker-compose.yml
...
  my-service:
    build:
      context: "."
      container_name: my_container
      command: ["/wait-for-it.sh", "mysql:3306", "--", [entrypoint function]]
...
```

**Comment by douglas-gibbons** [comment]
Thanks @agustisanchez - I like it. Depending on your setup, you might also copy wait-for-it.sh in as a mounted volume, such as this:

```
version: '3'

services:
  hello-world:
    image: ubuntu
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    command:
      - wait-for-it.sh
      - github.com:80
      - --
      - echo
      - "hello world"
```

**Comment by portolkyz** [comment]
Depending on the base image used there will be no netcat available in the container. The description pure bash conflicts in this case with the fact that netcat is no shell builtin. No offense intended. 

Cheers
Björn

**Comment by Tux1234** [comment]
Can you tell me what my Entrypoint is? 
Given are the following snippets.

#Dockerfile
```
FROM java:8
VOLUME /tmp
EXPOSE 8080
COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh
ADD target/App.jar App.jar.
ENTRYPOINT ["java","-jar","App.jar"]
```
Im not shure with my ENTRYPOINT. So ihave the follwoing 
#docker-compose.yml
```
...
  my-service:
    build:
      context: "."
      container_name: my_container
      command: ["./wait-for-mysql.sh", "mysql-docker-container:3306", "--", "java", "App.jar"]
....
```
Is the Entrypoint correct?

**Comment by Calimerico** [comment]
I think that your command should look like this:
command: ["./wait-for-mysql.sh", "mysql-docker-container:3306", "--", "sh", "-c", "java", "App.jar"]

**Comment by alexgivi** [comment]
to find out what is default endpoint - do next steps:
1. comment entrypoint config line in docker-compose.yml
2. start service (`docker-compose up -d`)
3. inspect service (`docker inspect my_container`) and find info about entrypoint. also it's possible to view  entrypoint via `docker ps`, but string is truncated.
4. modify your entrypoint: "wait-for-it mysql-docker-container:3306 -- default-entrypoint", replace "default-entrypoint" to your actual command

**Comment by yaoyuanyy** [comment]
> In order to use it with Docker and docker-compose,
> place it alongside `Dockerfile`, build it into the image with exec permissions and reference it in `docker-compose.yml`.
> 
> ```
> - Dockerfile
> - wait-for-it.sh
> ```
> 
> ```dockerfile
> #Dockerfile
> ...
> COPY wait-for-it.sh /wait-for-it.sh
> RUN chmod +x /wait-for-it.sh
> ...
> ```
> 
> ```yaml
> #docker-compose.yml
> ...
>   my-service:
>     build:
>       context: "."
>       container_name: my_container
>       command: ["/wait-for-it.sh", "mysql:3306", "--", [entrypoint function]]
> ...
> ```

@agustisanchez what is the "entrypoint function"  in docker-compose.yml

**Comment by yaoyuanyy** [comment]
@agustisanchez if i want to run a java project, what is the "entrypoint function"

**Comment by alexgivi** [comment]
https://docs.docker.com/compose/compose-file/#command
https://docs.docker.com/compose/compose-file/#entrypoint
there is some difference between command and entrypoint.
personally I prefer to use entrypoint config and not to use command.

**Comment by jakzal** [comment]
Multistage builds can be leveraged to install wait-for-it with apt-get:

```
FROM debian:buster-slim as wait-for-it
RUN apt-get update && apt-get install -y "wait-for-it"

FROM debian:buster-slim
COPY --from=wait-for-it /usr/bin/wait-for-it /usr/bin/wait-for-it
```

If there was an official docker image for wait-for-it (i.e. wait-for-it/wait-for-it) we could potentially do:

```
FROM debian:buster-slim
COPY --from=wait-for-it/wait-for-it /usr/bin/wait-for-it /usr/bin/wait-for-it
```

**Comment by kunal-bhatia** [comment]
Is it possible to use it with google distroless java images?

**Comment by mdkalish** [comment]
For a dependency that you don't need to build (i.e. also create Dockerfile and specify context), you can make it work with the volumes config only: 

1. `chmod 755 wait-for-it.sh` 
2.
```
# docker-compose.yml
…
volumes:
  - "./wait-for-it.sh:/wait-for-it.sh:ro"
…
```

Good to know: 
- Bind mounts keep the host's permissions[[source](https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker/29251160#29251160)], so step 1) is obligatory.
- The read-only (`ro`) segment is optional.

**Comment by ncjones** [comment]
wait-for-it.sh is not trapping SIGTERM so, to be able to gracefully stop a service that is stuck waiting, the stop signal needs to be overridden in docker-compose.yml:
```yaml
version: '3'

services:
  wait-for-app:
    image: ubuntu
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    command: wait-for-it.sh app:8080 -- echo ok
    stop_signal: SIGINT
```
