### ISSUE TITLE
i suggest wait-for-it support multiple condition

### ISSUE THREAD

**Issue by junneyang** [vishnubob/wait-for-it#58]
i suggest wait-for-it support multiple condition
example:
./wait-for-it.sh  mysql:3306 redis:6379

**Comment by douglas-gibbons** [comment]
Thanks @junneyang  - that would indeed be great.

The script is becoming a little large, so I hesitant to add any new functionality. It'll have to be `./wait-for-it.sh mysql:3306 && ./wait-for-it.sh redis:3306`  for now!

**Comment by thiagoloureiro** [comment]
any advice to use in a dockerfile this example?

**Comment by freaz** [comment]
Not sure how it should be useful in `Dockerfile`, but in `docker-compose.yml` you can use it like this:

```yaml
myapp:
  # ...
  command: bash -c "wait-for-it db:4567 && wait-for-it redis:6379 && ./start.sh"
```
